### ISSUE TITLE
Suggestion for licensing

### ISSUE THREAD

**Issue by HoangTheBoss** [you-create/three.js-sketches#5]
### I would suggest using GNU General Public License v3.0 (or GNU GPLv3).

> "Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. "

This would allow people to share and improve the repo.

More information [here](https://choosealicense.com/licenses/gpl-3.0/).

**Comment by you-create** [comment]
Hi @HoangTheBoss.

Thanks for the suggestion! I appreciate it. :+1:

I love the GNU GPLv3 (it can be used to license food recipes!). But unfortunately, the GNU GPLv3, as well as **_any_** open source license, cannot be used to license this repository. That is because some textures used in the repository are photographs taken from Textures.com. Term _h_, section _6.3_, article _6_ of [the Textures.com's Terms of Service](https://www.textures.com/terms-of-use.html) reads:

>  You are **not** permitted to: release the Content or derivative products with Content under Open Source Licences

As a pretty good boy when it comes to copyright, I have to make my work's licensing comply with the terms set for whatever my work uses.

In fact, I think that _not_ giving this repository a license is actually one of the most reasonable licensing solutions in this case. My sketches (consider that these are creative works) are somewhat my trademark, so they probably should not get interferences from other people. On the other hand, I make the source code public for educational purposes (okay, "educational purposes" sounds quite cheesy because I think no one will really give a damn about my sketches, but I cannot come up with anything better). Other people can fork this repository and they can secretly play with the code, but that's about it and that is also the barrier I want to put around these sketches. Just bare in mind that anyone can make sense of [the Fair Use doctrine](https://www.copyright.gov/fair-use/more-info.html).

Meanwhile, you can suggest some online texturing resources to me.
